### ISSUE TITLE
addOrUpdateObjectWithNotification: detecting updates as additions?

### ISSUE THREAD

**Issue by mcgregok** [Roobiq/RBQFetchedResultsController#32]
`- (void)addOrUpdateObjectWithNotification:(RLMObject *)object` seems to treat objects that are not from the same realm as additions otherwise it will treat them as updates.  Shouldn't it also be an update if an record with that primary key also exists in the realm for the RLMObject subclass and the instance passed in is not yet attached to a realm?  Realm will do an update in this case but I get a notification that it is an insert.

**Comment by mcgregok** [comment]
I'll take a stab at fixing it and putting up a pull request

**Comment by bigfish24** [comment]
Yeah that is true. This is making a bad assumption that if the object doesn't have a Realm instance attached it was just created and thus is an addition.

I missed this because RBQFRC internally doesn't need to know if it was an addition or a change. It treats all the notifications the same since a change could mean an addition in terms of the tableview that the FRC is backing (i.e. you change data so object now matches the predicate).

If you don't mind taking a stab in a PR, that would be great!

**Comment by mcgregok** [comment]
Opened a PR in the RBQRealmNotificationManager repo and welcoming feedback (https://github.com/Roobiq/RBQRealmNotificationManager/pull/1).  I likely could have simplified the code by including the RLMObject+Utilities and using primaryKeyValueForObject but didn't want to include the category from another category.  let me know if there is anything you want me to address before merging it in.  Thanks!

**Comment by bigfish24** [comment]
Ok, added some comments in the PR, thanks for doing this!

**Comment by bigfish24** [comment]
Ok will pull the submodules in with your fixes and create a new release.

**Comment by bigfish24** [comment]
Fixed in https://github.com/Roobiq/RBQFetchedResultsController/releases/tag/v1.8.9.5
