### ISSUE TITLE
KVO for Automatic Change Reporting?

### ISSUE THREAD

**Issue by bcapps** [Roobiq/RBQFetchedResultsController#39]
I see that you added a KVO branch to KVO List properties, but there may be another use that could allow you to automatically report changes. If, whenever an object was added or updated through the `addWithNotification:` method, you called `objectSchema` on the object and retrieved the property names from that, you could observe changes to all properties of every object - automatically. You could then stop observing when the object it is deleted.

This could potentially allow the elimination of the need for manual change reporting.

**Comment by bigfish24** [comment]
Well in theory yes you could, but the issue is that you will need to create and hold a reference to all of these objects for the entire time you are listening for changes. This is quite different and in my opinion more challenging than calling `didChangeObject:` or using `changeWithNotification:`. You lose all the benefits of lazy loading because of this.

Internally at Realm we are working on object change notifications that will replace the `RBQNotificationManager`. KVO was a first step, but really isn't the perfect fit. I was testing more around the use case that a `RLMArray` was backing a `UITableView` and you could then use KVO on the `RLMArray`.

**Comment by bcapps** [comment]
Cool, thanks for the explanation.
