### ISSUE TITLE
Cant create RBQFetchRequest with nil predicate.

### ISSUE THREAD

**Issue by ambas** [Roobiq/RBQFetchedResultsController#4]
When i create RBQFetchRequest with nil predicate and create new object with `addOrUpdateObjectWithNotification`,it not notify change and  then I try to dig to the code and found that in `evaluateObject` if predicate are nil it will alway return false.

Is this bug or i missing something.
Sorry for my bad english.

**Comment by bigfish24** [comment]
Sorry about this, I didn't realize there was a use case for a nil predicate? Can you explain the use case?

**Comment by ambas** [comment]
In my case I think if I set predicate to nil it mean I want all object form entity name that I set to `fetchRequestWithEntityName` parameter.I'm not sure this is a good way for do something like this :persevere:

**Comment by bigfish24** [comment]
Got it, I will update the code to support nil as a predicate. `evaluateObject:` will use the predicate if it is available and if not it will just verify if the object is of the same class as the RBQFetchRequest was setup as. This will take into account the changes from https://github.com/Roobiq/RBQFetchedResultsController/issues/3 to support Swift since class names were an issue there.

**Comment by bigfish24** [comment]
Ok this issue should be fixed in v1.7.4: https://github.com/Roobiq/RBQFetchedResultsController/releases

**Comment by bachirelkhoury** [comment]
Almost a year later, not sure that's supported still.
FetchRequest still requires an NSPredicate.
