### ISSUE TITLE
delegate doesn't seem to respond

### ISSUE THREAD

**Issue by jasper-ch-chan** [Roobiq/RBQFetchedResultsController#63]
I'm currently struggling to integrate FBQFetchedResultsController into my project. The FRC fetches, but it doesn't dynamically update itself to show the new information because the delegates aren't being called. I did set the FRC's delegate to my view controller. I'm not sure what else I could be missing... Has anyone else run into this problem?

**Comment by bigfish24** [comment]
@jasper-ch-chan are you using `RBQRealmNotificationManager` and `RBQRealmChangeLogger` when making changes to the Realm?

There are various convenience methods to make this easy, but `RBQFetchedResultsController` can't calculate the changes without this since Realm doesn't yet support fine-grained notifications.

**Comment by jasper-ch-chan** [comment]
@bigfish24 It is as you said. It appears the problem is because I need to use the functions addObjectWithNotification, and other corresponding functions to register the changes.

**Comment by bigfish24** [comment]
@jasper-ch-chan cool, glad things are working now
